# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'progress_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Progress(object):
    def setupUi(self, Progress):
        Progress.setObjectName("Progress")
        Progress.setWindowModality(QtCore.Qt.ApplicationModal)
        Progress.resize(440, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Progress.sizePolicy().hasHeightForWidth())
        Progress.setSizePolicy(sizePolicy)
        Progress.setMinimumSize(QtCore.QSize(440, 100))
        Progress.setMaximumSize(QtCore.QSize(440, 100))
        Progress.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Progress.setWindowTitle("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Progress.setWindowIcon(icon)
        Progress.setModal(True)
        self.progressBar = QtWidgets.QProgressBar(Progress)
        self.progressBar.setGeometry(QtCore.QRect(20, 40, 400, 25))
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(Progress)
        self.label.setGeometry(QtCore.QRect(20, 10, 400, 25))
        self.label.setText("")
        self.label.setObjectName("label")
        self.error_label = QtWidgets.QLabel(Progress)
        self.error_label.setGeometry(QtCore.QRect(20, 70, 400, 25))
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")

        self.retranslateUi(Progress)
        QtCore.QMetaObject.connectSlotsByName(Progress)

    def retranslateUi(self, Progress):
        pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Progress = QtWidgets.QDialog()
    ui = Ui_Progress()
    ui.setupUi(Progress)
    Progress.show()
    sys.exit(app.exec_())
